var GetRandomInt = require('./utils.js').GetRandomInt;

// Maximum upload/download speeds for mock data
const MIN_SPEED = 0;
const MAX_SPEED = 90000000;
var RID = -1;    // For /sync/maindata endpoint

function getRandomId() {
    return Math.random().toString(36).substring(15);
}

/**Mock data for /sync/maindata endpoint */
function GetMainData(){
    RID += 1;
    return (
        {
            "categories": {},
            "full_update": true,
            "rid": RID,
            "server_state": {
                "alltime_dl": 134924863044,
                "alltime_ul": 169885275053,
                "average_time_queue": 3787,
                "connection_status": "connected",
                "dht_nodes": 393,
                "dl_info_data": 0,
                "dl_info_speed": GetRandomInt(MIN_SPEED, MAX_SPEED),
                "dl_rate_limit": 0,
                "free_space_on_disk": 191069335552,
                "global_ratio": "1.25",
                "queued_io_jobs": 0,
                "queueing": true,
                "read_cache_hits": "26.34",
                "read_cache_overload": "0",
                "refresh_interval": 1500,
                "total_buffers_size": 66060288,
                "total_peer_connections": 10,
                "total_queued_size": 0,
                "total_wasted_session": 0,
                "up_info_data": 2881417756,
                "up_info_speed": GetRandomInt(MIN_SPEED, MAX_SPEED),
                "up_rate_limit": 0,
                "use_alt_speed_limits": false,
                "write_cache_overload": "0"
            },
            "torrents": {
                "03b82ec41283e57ffb5a284e9a7773199dddc72a": {
                    "added_on": 1561931538,
                    "amount_left": 0,
                    "auto_tmm": false,
                    "category": "",
                    "completed": 6211419,
                    "completion_on": 1561931543,
                    "dl_limit": -1,
                    "dlspeed": GetRandomInt(MIN_SPEED, MAX_SPEED),
                    "downloaded": 7262278,
                    "downloaded_session": 0,
                    "eta": 8640000,
                    "f_l_piece_prio": false,
                    "force_start": true,
                    "last_activity": 1583846813,
                    "magnet_uri": "magnet #0",
                    "max_ratio": -1,
                    "max_seeding_time": -1,
                    "name": "The Quick Brown Fox",
                    "num_complete": 33,
                    "num_incomplete": 1,
                    "num_leechs": 0,
                    "num_seeds": 0,
                    "priority": 0,
                    "progress": 1,
                    "ratio": 0.2930033799312006,
                    "ratio_limit": -2,
                    "save_path": "D:\\Jumped Over\\Some Lazy Dog\\",
                    "seeding_time_limit": -2,
                    "seen_complete": 1583845906,
                    "seq_dl": false,
                    "size": 6211419,
                    "state": "forcedUP",
                    "super_seeding": false,
                    "tags": "",
                    "time_active": 5328405,
                    "total_size": 6211419,
                    "tracker": "some tracker #0",
                    "up_limit": -1,
                    "uploaded": 2127872,
                    "uploaded_session": 0,
                    "upspeed": GetRandomInt(MIN_SPEED, MAX_SPEED)
                },
                "0daea5cece5": {
                    "added_on": 1574566015,
                    "amount_left": 0,
                    "auto_tmm": false,
                    "category": "",
                    "completed": 209869298,
                    "completion_on": 1574566120,
                    "dl_limit": -1,
                    "dlspeed": GetRandomInt(MIN_SPEED, MAX_SPEED),
                    "downloaded": 210629655,
                    "downloaded_session": 0,
                    "eta": 8640000,
                    "f_l_piece_prio": false,
                    "force_start": true,
                    "last_activity": 1583690488,
                    "magnet_uri": "magnet_uri",
                    "max_ratio": -1,
                    "max_seeding_time": -1,
                    "name": "Some show #1 with super loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong name",
                    "num_complete": 18,
                    "num_incomplete": 1,
                    "num_leechs": 0,
                    "num_seeds": 0,
                    "priority": 0,
                    "progress": 1,
                    "ratio": 1.0442750048657679,
                    "ratio_limit": -2,
                    "save_path": "A:\\Movies & TV\\Some show\\",
                    "seeding_time_limit": -2,
                    "seen_complete": 1580860752,
                    "seq_dl": false,
                    "size": 209869298,
                    "state": "forcedUP",
                    "super_seeding": false,
                    "tags": "",
                    "time_active": 718637,
                    "total_size": 209869298,
                    "tracker": "https some tracker",
                    "up_limit": -1,
                    "uploaded": 219955284,
                    "uploaded_session": 0,
                    "upspeed": GetRandomInt(MIN_SPEED, MAX_SPEED)
                },
                "0f4eefe81227d7211b31a500144fe6a48b5b7d46": {
                    "added_on": 1574566016,
                    "amount_left": 0,
                    "auto_tmm": false,
                    "category": "",
                    "completed": 310964698,
                    "completion_on": 1574566096,
                    "dl_limit": -1,
                    "dlspeed": GetRandomInt(MIN_SPEED, MAX_SPEED),
                    "downloaded": 311199215,
                    "downloaded_session": 0,
                    "eta": 8640000,
                    "f_l_piece_prio": false,
                    "force_start": true,
                    "last_activity": 1583690567,
                    "magnet_uri": "magnet",
                    "max_ratio": -1,
                    "max_seeding_time": -1,
                    "name": "Another show #2 with decently-sized name",
                    "num_complete": 12,
                    "num_incomplete": 1,
                    "num_leechs": 0,
                    "num_seeds": 0,
                    "priority": 0,
                    "progress": 1,
                    "ratio": 0.5514229655110152,
                    "ratio_limit": -2,
                    "save_path": "B:\\TV\\Some show #2\\",
                    "seeding_time_limit": -2,
                    "seen_complete": 1583660691,
                    "seq_dl": false,
                    "size": 310964698,
                    "state": "forcedUP",
                    "super_seeding": false,
                    "tags": "",
                    "time_active": 876906,
                    "total_size": 310964698,
                    "tracker": "https tracker",
                    "up_limit": -1,
                    "uploaded": 171602394,
                    "uploaded_session": 0,
                    "upspeed": GetRandomInt(MIN_SPEED, MAX_SPEED)
                },
                "16ce8f1b00e2b0e0fbc4dc8b46e629c8cd2ef0e1": {
                    "added_on": 1555812938,
                    "amount_left": 0,
                    "auto_tmm": false,
                    "category": "",
                    "completed": 966283000,
                    "completion_on": 1555813080,
                    "dl_limit": -1,
                    "dlspeed": GetRandomInt(MIN_SPEED, MAX_SPEED),
                    "downloaded": 966470211,
                    "downloaded_session": 0,
                    "eta": 8640000,
                    "f_l_piece_prio": false,
                    "force_start": true,
                    "last_activity": 1583770394,
                    "magnet_uri": "another magnet",
                    "max_ratio": -1,
                    "max_seeding_time": -1,
                    "name": "Ubuntu Debian 18.04 LTS",
                    "num_complete": 14,
                    "num_incomplete": 1,
                    "num_leechs": 0,
                    "num_seeds": 0,
                    "priority": 0,
                    "progress": 1,
                    "ratio": 1.1216271900179653,
                    "ratio_limit": -2,
                    "save_path": "C:\\Downloads\\Images\\",
                    "seeding_time_limit": -2,
                    "seen_complete": 1566641377,
                    "seq_dl": false,
                    "size": 966283000,
                    "state": "forcedUP",
                    "super_seeding": false,
                    "tags": "",
                    "time_active": 10218680,
                    "total_size": 966283000,
                    "tracker": "https my tracker #3",
                    "up_limit": -1,
                    "uploaded": 1084019267,
                    "uploaded_session": 0,
                    "upspeed": GetRandomInt(MIN_SPEED, MAX_SPEED)
                }
            }
        }
    );
}

module.exports.GetMainData = GetMainData;